apiVersion: ENC[AES256_GCM,data:Ciw=,iv:l8BrQo82CPOLRSN5pFkh5WQr9V0m0ryXbSt6fCOfU18=,tag:NWLQZCyzx5Rc+oEAA4cJNg==,type:str]
kind: ENC[AES256_GCM,data:mwy1T1sr,iv:ETdJykc8khJlXBfG7lmAuJvtVS5bh2ZP7lkKjPBJSMo=,tag:WpUzxTHCasS8dUUv9tiKLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xl01cwr5CCFyrWRAArKo,iv:cC9UyEAXRB5MAGsjwHGvvU/guUwR0drDAE3SHYW7SAo=,tag:M2Vm4BlFcBL1CYTDpgeMOg==,type:str]
    namespace: ENC[AES256_GCM,data:PPFmAA==,iv:AxuvrraV/uLjm+OmMF2mrvJj9mGQWaqRn9VSwMflWG0=,tag:iQbzTiVyXyH5AJl0jNlFvA==,type:str]
stringData:
    PSTN_GW_IP: ENC[AES256_GCM,data:i9BnzLj+90+Q,iv:x3uAZZwxRNSXqC0LHQ0xh9itCRArlRIOu5idcy09OYA=,tag:tKQWYtFIdPf1m/J7ev8UFA==,type:str]
sops:
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM2pDSDZzT3FCUTZ3WkN3
            MEJBRFo2cWJrNXlmblJQd2NLaTdmMUVDUkdVClNmMUR4ZWRQY3p5NXNtZnNXV29Z
            Nk90VjY3Rkl5eVdQRko2T1Y0djVwS3MKLS0tIGxBWEVHandOV2tWbTZ0TVFwWDdJ
            dk80U3FhSEZpOGJZM2JHakJvVGxxUE0Kn3LSVnbTWODN5kpBH2NIa1ieUeGs7tyh
            wRDs/MHR+GcXvMhsW+Y5fq5fNCWnaqmLxfdSurxh9osTV32PEnk1Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T05:56:33Z"
    mac: ENC[AES256_GCM,data:/nLH549DXZMZ6kalhE/MliYGS8j54kwd900XPSvS6aFHxdLSrbD6XWNe6VxOk53sb2IZtYbMJMuENKM5uayZOA+A6xVogUh93xAm1RlrHNEcTZCoD4Cgx4JK3mzGB/SNBonsA2U3yxJrjsjFoOdY9UIO5HOVL7u7BQ51VaOxY2k=,iv:aUTxqddITyymAwa/VtkAlmbtpt3i890kyGcwF3ta9lo=,tag:/dKXo/1OLot+OvWXRpEDAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
