apiVersion: ENC[AES256_GCM,data:Ciw=,iv:l8BrQo82CPOLRSN5pFkh5WQr9V0m0ryXbSt6fCOfU18=,tag:NWLQZCyzx5Rc+oEAA4cJNg==,type:str]
kind: ENC[AES256_GCM,data:mwy1T1sr,iv:ETdJykc8khJlXBfG7lmAuJvtVS5bh2ZP7lkKjPBJSMo=,tag:WpUzxTHCasS8dUUv9tiKLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xl01cwr5CCFyrWRAArKo,iv:cC9UyEAXRB5MAGsjwHGvvU/guUwR0drDAE3SHYW7SAo=,tag:M2Vm4BlFcBL1CYTDpgeMOg==,type:str]
    namespace: ENC[AES256_GCM,data:PPFmAA==,iv:AxuvrraV/uLjm+OmMF2mrvJj9mGQWaqRn9VSwMflWG0=,tag:iQbzTiVyXyH5AJl0jNlFvA==,type:str]
stringData:
    PSTN_GW_IP: ENC[AES256_GCM,data:CQg1/Dk7+q0Eaw==,iv:gz7XinHw+x7jgf5cXyEcNWjhW9TMNVAfYhdGjjed9yw=,tag:CdMWbLpIuQGbUivI91bjRg==,type:str]
sops:
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM2pDSDZzT3FCUTZ3WkN3
            MEJBRFo2cWJrNXlmblJQd2NLaTdmMUVDUkdVClNmMUR4ZWRQY3p5NXNtZnNXV29Z
            Nk90VjY3Rkl5eVdQRko2T1Y0djVwS3MKLS0tIGxBWEVHandOV2tWbTZ0TVFwWDdJ
            dk80U3FhSEZpOGJZM2JHakJvVGxxUE0Kn3LSVnbTWODN5kpBH2NIa1ieUeGs7tyh
            wRDs/MHR+GcXvMhsW+Y5fq5fNCWnaqmLxfdSurxh9osTV32PEnk1Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T17:31:49Z"
    mac: ENC[AES256_GCM,data:u2ns4M99om16AXA8iARD2yGuXhHhYnewxfEuQ1qIF2KKcELZTZJHitu1WVDREKpPP/zQZR4SSBkIfBUjR6iWFUgqH2KkDGuaTnPJchFDDR5R7QytJe9oxu1DMaz4BX0H94SsDitSNJl9UZYfY4807ALgDMs/YZcG2a6OrTStyOE=,iv:V/TcEhyKTBpVBRB4cw2QV7FC1KaKh68ONloJcL9n1sg=,tag:hEnmPoy1WmDVQNqFcG7w6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
