apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: kamailio-l2-net
  namespace: voip
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "kamailio-l2-net",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.40.50/24",
        "range_end": "10.0.40.59",
        "exclude": []
      }
    }