apiVersion: ENC[AES256_GCM,data:dkE=,iv:2535E42+hmnB1FEXbLAYTME1R/UUaFhf/vMd69PpcGc=,tag:3Kjlo9VHRt929+l9h1xdEQ==,type:str]
kind: ENC[AES256_GCM,data:9/VX8cOw,iv:BnlXO0sL4q1LB1GJGNCXdS2TJP1Cd017FllwTSmMtRg=,tag:lAAbr194EabLgaQHjxGOSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OR36gx0LkEDSC94ZzqTi,iv:ze69EvSM+44YkKoHK2mm+i5CnIc0pHcTmZ4hi16txdc=,tag:UqVma8nSQ3A2lk19Z/a4qw==,type:str]
    namespace: ENC[AES256_GCM,data:fYCmkRTloIkLG60=,iv:afgRsegCfRSP8OulVY20t4+KRduymaWFYluZK8hM0Pw=,tag:QRvDncw9y3qWJ91+e03Aqg==,type:str]
stringData:
    TZ: ENC[AES256_GCM,data:XNbKe9R8C9Y27u9KXTIc,iv:zCrzWTTn7WGzUSCEw3zmTDejXUA7ftVYWjKHE57M6W8=,tag:QesD671QaDvPhnB+P1dUJg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:Dr2/axJKu8vVZtDZnA==,iv:/xlPraqTBXG6Bv2haCoWUVCDHsOAxdmwAB/XW990fME=,tag:e2b41IlTgxaQhtStq0SZpQ==,type:str]
sops:
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYkI0WmMrWFYzUEh5SHpN
            R2x6b2FVTnBZNXZCdkMwUHdaTGdIcW1TaEhnCk1qTFJRdWxZZ3pBbXBLWU5DdFU0
            RktDeTB3ODFJN0czanYveU5NaDVKWk0KLS0tIHo5Uy9la2d5ZzRGcEp2cWszZzRC
            U3lGZFZCQVlhWnpkMDgvdDRDa0pjQmsKB6bcr1njCnAcQfXUWjZTH4PhCNv/+oyf
            o0in62TlyBh4qBsegSHVwRARLy+jzDAzYOk9wMhrKdc5j5uP9O6xmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:15:49Z"
    mac: ENC[AES256_GCM,data:dv11wbBh+iqI6vgnx3XSDIsHMJVzmTN+v4HRtSE6AQ+PWF0VqgkktobLLQoObxzwKgjM5u9xFvWIywYPwETmrzk/VY6KqCyEpkHeDO5W6oAXdsd6GmoaLz44ozVHy6Eb1T3BgNyShuLWMYdBX5ZQKWgWsI8qPpxyY4o6iB8Iimc=,iv:b8w0IDbbhxvIqImCO5pCZrYekOUlvSC+Ytc6fNoTkXM=,tag:R+Cn8fuMIkDnYEKrjCNlIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
